language: node_js
node_js:
  - 'node'
before_install:
  - rvm use 2.2
  - gem install bundler
  - npm install -g bower
  - npm install -g grunt-cli
install:
  - bundle install
  - yarn
before_script: bower install
script: grunt
after_success: grunt deploy
branches:
  only:
    - master
notifications:
  slack: matallin:WiB9wQ4XqhLjMD14aI5mNEwX
