language: ruby
rvm:
  - 2.3.0
before_install:
  - npm install -g npm@latest
  - npm install -g grunt-cli
  - npm install -g bower
install:
  - bundle install
  - npm install
  - bower install
script: grunt deploy
