language: node_js
cache:
  - bundler
  - yarn
node_js:
  - 'node'
before_install:
  - rvm install ruby-2.2.0
  - gem install bundler
  - npm install -g bower
  - npm install -g grunt-cli
install:
  - bundle install
  - npm install
before_script: bower install
script: grunt
after_success: grunt deploy
branches:
  only:
    - master
notifications:
  slack: matallin:WiB9wQ4XqhLjMD14aI5mNEwX
