# Site settings
title: "Carlos Matallín"
description: "Code, design, and mountains"
baseurl: ""
url: "http://matall.in"
gems:
  - jekyll-sitemap

# Build settings
source: 'app'
destination: 'dist'
markdown: kramdown
permalink: pretty

years: 28

# analytics_property_id: ''

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title/
