# Site settings
title: "Carlos Matallín"
description: "Code, design, and mountains"
baseurl: ""
url: "https://matall.in"

# Build settings
source: "app"
destination: "dist"
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

birthday: "1988-02-02"

# analytics_property_id: ''

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title/
