# Site settings
title: "Carlos Matallín"
description: "Code, design, and mountains"
baseurl: ""
url: "http://matall.in"
gems:
  - jekyll-sitemap

# Build settings
source: 'app'
destination: 'dist'
markdown: kramdown
permalink: pretty

years: 27

# analytics_property_id: ''
