defaults: &defaults
  working_directory: ~/matall.in
version: 2
jobs:
  build_and_test:
    <<: *defaults
    docker:
      - image: circleci/ruby:latest-node-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            gem install bundler
            sudo yarn global add gulp-cli
            bundle install --path vendor/bundle
            yarn install --no-lockfile
      - run:
          name: Run linter
          command: yarn run lint
      - run:
          name: Run tests
          command: yarn run test
      - run:
          name: Build
          command: |
            bundle --path vendor/bundle
            if [ ${CIRCLE_BRANCH} == "master" ]; then
              JEKYLL_ENV=production yarn run build
            else
              JEKYLL_ENV=staging yarn run build
            fi
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/matall.in/vendor/bundle
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/matall.in/node_modules
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  release:
    <<: *defaults
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: sudo yarn global add gh-release
      - run:
          name: Publish Release on GitHub
          command: gh-release -y
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  deploy:
    <<: *defaults
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy to S3
          command: |
            if [ ${CIRCLE_BRANCH} == "master" ]; then
              aws s3 sync --acl public-read dist/ s3://${AWS_BUCKET} --delete --exclude "*" --include "*.html" --include "*.ico" --include "sw.js" --include "manifest.json" --include "*.png" --include "*.txt" --include "*.xml" --include "img/*" --cache-control "max-age=0, public"
              aws s3 sync --acl public-read dist/ s3://${AWS_BUCKET} --delete --exclude "*" --include "css/*" --include "js/*" --cache-control "max-age=31536000, public" --expires $(date -d "+1 year" -u +%Y-%m-%dT%H:%M:%SZ)
            else
              aws s3 sync --acl public-read dist/ s3://${AWS_BUCKET_STAGING} --delete --exclude "*" --include "*.html" --include "*.ico" --include "sw.js" --include "manifest.json" --include "*.png" --include "*.txt" --include "*.xml" --include "img/*" --cache-control "max-age=0, public"
              aws s3 sync --acl public-read dist/ s3://${AWS_BUCKET_STAGING} --delete --exclude "*" --include "css/*" --include "js/*" --cache-control "max-age=31536000, public" --expires $(date -d "+1 year" -u +%Y-%m-%dT%H:%M:%SZ)
            fi
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
      - release:
          requires:
            - deploy
          filters:
            branches:
              only: master
