defaults: &defaults
  working_directory: ~/matall.in
version: 2
jobs:
  build_and_test:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5-node-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    environment:
      - NODE_ENV: production
    steps:
      - checkout
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: bundle install --path vendor/bundle
      - run: sudo yarn global add gulp-cli
      - run: yarn install
      - run:
          name: Run linter
          command: yarn run lint
      - run:
          name: Run tests
          command: yarn run test
      - run: bundle --path vendor/bundle
      - run:
          name: Build
          command: |
            if [ ${CIRCLE_BRANCH} == "master" ]; then
              JEKYLL_ENV=production yarn run build
            else
              JEKYLL_ENV=staging yarn run build
            fi
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/matall.in/vendor/bundle
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/matall.in/node_modules
      - save_cache:
          key: v1-assets-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/matall.in/dist
  deploy:
    <<: *defaults
    machine:
      enabled: true
    steps:
      - restore_cache:
          key: v1-assets-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Deploy to S3
          command: |
            if [ ${CIRCLE_BRANCH} == "master" ]; then
              aws s3 sync --acl public-read dist/ s3://${AWS_BUCKET} --delete --exclude "*" --include "*.html" --include "*.txt" --include "*.xml" --cache-control "max-age=0, public"
              aws s3 sync --acl public-read dist/ s3://${AWS_BUCKET} --delete --exclude "*" --include "*.ico" --include "*.png" --include "css/*" --include "js/*" --include "img/*" --cache-control "max-age=31536000, public" --expires $(date -d "+1 year" -u +%Y-%m-%dT%H:%M:%SZ)
            else
              aws s3 sync --acl public-read dist/ s3://${AWS_BUCKET_STAGING} --delete --exclude "*" --include "*.html" --include "*.txt" --include "*.xml" --cache-control "max-age=0, public"
              aws s3 sync --acl public-read dist/ s3://${AWS_BUCKET_STAGING} --delete --exclude "*" --include "*.ico" --include "*.png" --include "css/*" --include "js/*" --include "img/*" --cache-control "max-age=31536000, public" --expires $(date -d "+1 year" -u +%Y-%m-%dT%H:%M:%SZ)
            fi
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
